"""
Mapeamento completo dos 66 livros da Tradução do Novo Mundo (NWT).
Slugs em português (padrão jw.org/pt).
"""

LIVROS_BIBLIA = [
    # ─── ESCRITURAS HEBRAICO-ARAMAICAS (39 livros) ───
    {"ordem": 1,  "nome": "Gênesis",              "slug": "genesis",          "abrev": "Gên",  "testamento": "hebraico", "capitulos": 50},
    {"ordem": 2,  "nome": "Êxodo",                "slug": "exodo",            "abrev": "Êx",   "testamento": "hebraico", "capitulos": 40},
    {"ordem": 3,  "nome": "Levítico",             "slug": "levitico",         "abrev": "Le",   "testamento": "hebraico", "capitulos": 27},
    {"ordem": 4,  "nome": "Números",              "slug": "numeros",          "abrev": "Núm",  "testamento": "hebraico", "capitulos": 36},
    {"ordem": 5,  "nome": "Deuteronômio",         "slug": "deuteronomio",     "abrev": "De",   "testamento": "hebraico", "capitulos": 34},
    {"ordem": 6,  "nome": "Josué",                "slug": "josue",            "abrev": "Jos",  "testamento": "hebraico", "capitulos": 24},
    {"ordem": 7,  "nome": "Juízes",               "slug": "juizes",           "abrev": "Jz",   "testamento": "hebraico", "capitulos": 21},
    {"ordem": 8,  "nome": "Rute",                 "slug": "rute",             "abrev": "Ru",   "testamento": "hebraico", "capitulos": 4},
    {"ordem": 9,  "nome": "1 Samuel",             "slug": "1-samuel",         "abrev": "1Sa",  "testamento": "hebraico", "capitulos": 31},
    {"ordem": 10, "nome": "2 Samuel",             "slug": "2-samuel",         "abrev": "2Sa",  "testamento": "hebraico", "capitulos": 24},
    {"ordem": 11, "nome": "1 Reis",               "slug": "1-reis",           "abrev": "1Rs",  "testamento": "hebraico", "capitulos": 22},
    {"ordem": 12, "nome": "2 Reis",               "slug": "2-reis",           "abrev": "2Rs",  "testamento": "hebraico", "capitulos": 25},
    {"ordem": 13, "nome": "1 Crônicas",           "slug": "1-cronicas",       "abrev": "1Cr",  "testamento": "hebraico", "capitulos": 29},
    {"ordem": 14, "nome": "2 Crônicas",           "slug": "2-cronicas",       "abrev": "2Cr",  "testamento": "hebraico", "capitulos": 36},
    {"ordem": 15, "nome": "Esdras",               "slug": "esdras",           "abrev": "Esd",  "testamento": "hebraico", "capitulos": 10},
    {"ordem": 16, "nome": "Neemias",              "slug": "neemias",          "abrev": "Ne",   "testamento": "hebraico", "capitulos": 13},
    {"ordem": 17, "nome": "Ester",                "slug": "ester",            "abrev": "Est",  "testamento": "hebraico", "capitulos": 10},
    {"ordem": 18, "nome": "Jó",                   "slug": "jo",               "abrev": "Jó",   "testamento": "hebraico", "capitulos": 42},
    {"ordem": 19, "nome": "Salmos",               "slug": "salmos",           "abrev": "Sal",  "testamento": "hebraico", "capitulos": 150},
    {"ordem": 20, "nome": "Provérbios",           "slug": "proverbios",       "abrev": "Pr",   "testamento": "hebraico", "capitulos": 31},
    {"ordem": 21, "nome": "Eclesiastes",          "slug": "eclesiastes",      "abrev": "Ec",   "testamento": "hebraico", "capitulos": 12},
    {"ordem": 22, "nome": "Cântico de Salomão",   "slug": "cantico-de-salomao", "abrev": "Cân", "testamento": "hebraico", "capitulos": 8},
    {"ordem": 23, "nome": "Isaías",               "slug": "isaias",           "abrev": "Is",   "testamento": "hebraico", "capitulos": 66},
    {"ordem": 24, "nome": "Jeremias",             "slug": "jeremias",         "abrev": "Je",   "testamento": "hebraico", "capitulos": 52},
    {"ordem": 25, "nome": "Lamentações",          "slug": "lamentacoes",      "abrev": "La",   "testamento": "hebraico", "capitulos": 5},
    {"ordem": 26, "nome": "Ezequiel",             "slug": "ezequiel",         "abrev": "Ez",   "testamento": "hebraico", "capitulos": 48},
    {"ordem": 27, "nome": "Daniel",               "slug": "daniel",           "abrev": "Da",   "testamento": "hebraico", "capitulos": 12},
    {"ordem": 28, "nome": "Oseias",               "slug": "oseias",           "abrev": "Os",   "testamento": "hebraico", "capitulos": 14},
    {"ordem": 29, "nome": "Joel",                 "slug": "joel",             "abrev": "Jl",   "testamento": "hebraico", "capitulos": 3},
    {"ordem": 30, "nome": "Amós",                 "slug": "amos",             "abrev": "Am",   "testamento": "hebraico", "capitulos": 9},
    {"ordem": 31, "nome": "Obadias",              "slug": "obadias",          "abrev": "Ob",   "testamento": "hebraico", "capitulos": 1},
    {"ordem": 32, "nome": "Jonas",                "slug": "jonas",            "abrev": "Jon",  "testamento": "hebraico", "capitulos": 4},
    {"ordem": 33, "nome": "Miquéias",             "slug": "miqueias",         "abrev": "Miq",  "testamento": "hebraico", "capitulos": 7},
    {"ordem": 34, "nome": "Naum",                 "slug": "naum",             "abrev": "Na",   "testamento": "hebraico", "capitulos": 3},
    {"ordem": 35, "nome": "Habacuque",            "slug": "habacuque",        "abrev": "Hab",  "testamento": "hebraico", "capitulos": 3},
    {"ordem": 36, "nome": "Sofonias",             "slug": "sofonias",         "abrev": "Sof",  "testamento": "hebraico", "capitulos": 3},
    {"ordem": 37, "nome": "Ageu",                 "slug": "ageu",             "abrev": "Ag",   "testamento": "hebraico", "capitulos": 2},
    {"ordem": 38, "nome": "Zacarias",             "slug": "zacarias",         "abrev": "Za",   "testamento": "hebraico", "capitulos": 14},
    {"ordem": 39, "nome": "Malaquias",            "slug": "malaquias",        "abrev": "Mal",  "testamento": "hebraico", "capitulos": 4},

    # ─── ESCRITURAS GREGAS CRISTÃS (27 livros) ───
    {"ordem": 40, "nome": "Mateus",               "slug": "mateus",           "abrev": "Mt",   "testamento": "grego", "capitulos": 28},
    {"ordem": 41, "nome": "Marcos",               "slug": "marcos",           "abrev": "Mr",   "testamento": "grego", "capitulos": 16},
    {"ordem": 42, "nome": "Lucas",                "slug": "lucas",            "abrev": "Lu",   "testamento": "grego", "capitulos": 24},
    {"ordem": 43, "nome": "João",                 "slug": "joao",             "abrev": "Jo",   "testamento": "grego", "capitulos": 21},
    {"ordem": 44, "nome": "Atos",                 "slug": "atos",             "abrev": "At",   "testamento": "grego", "capitulos": 28},
    {"ordem": 45, "nome": "Romanos",              "slug": "romanos",          "abrev": "Ro",   "testamento": "grego", "capitulos": 16},
    {"ordem": 46, "nome": "1 Coríntios",          "slug": "1-corintios",      "abrev": "1Co",  "testamento": "grego", "capitulos": 16},
    {"ordem": 47, "nome": "2 Coríntios",          "slug": "2-corintios",      "abrev": "2Co",  "testamento": "grego", "capitulos": 13},
    {"ordem": 48, "nome": "Gálatas",              "slug": "galatas",          "abrev": "Gál",  "testamento": "grego", "capitulos": 6},
    {"ordem": 49, "nome": "Efésios",              "slug": "efesios",          "abrev": "Ef",   "testamento": "grego", "capitulos": 6},
    {"ordem": 50, "nome": "Filipenses",           "slug": "filipenses",       "abrev": "Fil",  "testamento": "grego", "capitulos": 4},
    {"ordem": 51, "nome": "Colossenses",          "slug": "colossenses",      "abrev": "Col",  "testamento": "grego", "capitulos": 4},
    {"ordem": 52, "nome": "1 Tessalonicenses",    "slug": "1-tessalonicenses","abrev": "1Te",  "testamento": "grego", "capitulos": 5},
    {"ordem": 53, "nome": "2 Tessalonicenses",    "slug": "2-tessalonicenses","abrev": "2Te",  "testamento": "grego", "capitulos": 3},
    {"ordem": 54, "nome": "1 Timóteo",            "slug": "1-timoteo",        "abrev": "1Ti",  "testamento": "grego", "capitulos": 6},
    {"ordem": 55, "nome": "2 Timóteo",            "slug": "2-timoteo",        "abrev": "2Ti",  "testamento": "grego", "capitulos": 4},
    {"ordem": 56, "nome": "Tito",                 "slug": "tito",             "abrev": "Tit",  "testamento": "grego", "capitulos": 3},
    {"ordem": 57, "nome": "Filemom",              "slug": "filemon",          "abrev": "Flm",  "testamento": "grego", "capitulos": 1},
    {"ordem": 58, "nome": "Hebreus",              "slug": "hebreus",          "abrev": "He",   "testamento": "grego", "capitulos": 13},
    {"ordem": 59, "nome": "Tiago",                "slug": "tiago",            "abrev": "Tg",   "testamento": "grego", "capitulos": 5},
    {"ordem": 60, "nome": "1 Pedro",              "slug": "1-pedro",          "abrev": "1Pe",  "testamento": "grego", "capitulos": 5},
    {"ordem": 61, "nome": "2 Pedro",              "slug": "2-pedro",          "abrev": "2Pe",  "testamento": "grego", "capitulos": 3},
    {"ordem": 62, "nome": "1 João",               "slug": "1-joao",           "abrev": "1Jo",  "testamento": "grego", "capitulos": 5},
    {"ordem": 63, "nome": "2 João",               "slug": "2-joao",           "abrev": "2Jo",  "testamento": "grego", "capitulos": 1},
    {"ordem": 64, "nome": "3 João",               "slug": "3-joao",           "abrev": "3Jo",  "testamento": "grego", "capitulos": 1},
    {"ordem": 65, "nome": "Judas",                "slug": "judas",            "abrev": "Ju",   "testamento": "grego", "capitulos": 1},
    {"ordem": 66, "nome": "Apocalipse",           "slug": "apocalipse",       "abrev": "Ap",   "testamento": "grego", "capitulos": 22},
]

TOTAL_CAPITULOS = sum(l["capitulos"] for l in LIVROS_BIBLIA)
LIVROS_POR_SLUG = {l["slug"]: l for l in LIVROS_BIBLIA}
LIVROS_POR_NOME = {l["nome"].lower(): l for l in LIVROS_BIBLIA}
URL_BASE = "https://www.jw.org/pt/biblioteca/biblia/nwt/livros"
